### ISSUE TITLE
How to use somever instead of semVer?

### ISSUE THREAD

**Issue by Aniganesh** [some-ver/SomeVer#1]
I am trying to make a build tool using some ver but I am having issues integrating it with the rest of the code. Any idea on how I am supposed to download this package and use it in a nodejs project?

**Comment by pixelass** [comment]
Thank you for your interest in this project. Just use any version you like and you're good to go. 
There is no package for this repo yet. We might release one in the future, who knows.

<img src="https://user-images.githubusercontent.com/1148334/133913334-3555fef6-dfef-4d7f-99f0-cb43ef618ab4.jpeg" alt="trollface" width="100px"/>
